"""
Curated list of companies using Greenhouse, Lever, Ashby, or SmartRecruiters.
Pre-verified ATS slugs for direct API access.
"""

COMPANIES = [
    # =========================================================================
    # SMARTRECRUITERS COMPANIES
    # =========================================================================
    {"name": "Visa", "ats": "smartrecruiters", "slug": "visa"},
    {"name": "McDonald's", "ats": "smartrecruiters", "slug": "mcdonalds"},
    {"name": "Adidas", "ats": "smartrecruiters", "slug": "adidas"},
    {"name": "IKEA", "ats": "smartrecruiters", "slug": "ikea"},
    {"name": "Spotify", "ats": "smartrecruiters", "slug": "spotify"},
    {"name": "Bosch", "ats": "smartrecruiters", "slug": "bosch"},
    {"name": "Sephora", "ats": "smartrecruiters", "slug": "sephora"},
    {"name": "LinkedIn", "ats": "smartrecruiters", "slug": "linkedin"},
    {"name": "Equinix", "ats": "smartrecruiters", "slug": "equinix"},
    {"name": "Informatica", "ats": "smartrecruiters", "slug": "informatica"},
    {"name": "Square Enix", "ats": "smartrecruiters", "slug": "squareenix"},
    {"name": "Ubisoft", "ats": "smartrecruiters", "slug": "ubisoft"},
    
    # =========================================================================
    # GREENHOUSE COMPANIES (Verified)
    # =========================================================================
    # Elon Companies
    {"name": "xAI", "ats": "greenhouse", "slug": "xai"},
    {"name": "SpaceX", "ats": "greenhouse", "slug": "spacex"},
    {"name": "Neuralink", "ats": "greenhouse", "slug": "neuralink"},
    
    # Autonomous Vehicles
    {"name": "Waymo", "ats": "greenhouse", "slug": "waymo"},
    {"name": "Nuro", "ats": "greenhouse", "slug": "nuro"},
    {"name": "Lucid Motors", "ats": "greenhouse", "slug": "lucidmotors"},
    
    # Major Tech
    {"name": "Stripe", "ats": "greenhouse", "slug": "stripe"},
    {"name": "Airbnb", "ats": "greenhouse", "slug": "airbnb"},
    {"name": "Dropbox", "ats": "greenhouse", "slug": "dropbox"},
    {"name": "Pinterest", "ats": "greenhouse", "slug": "pinterest"},
    {"name": "Lyft", "ats": "greenhouse", "slug": "lyft"},
    {"name": "Instacart", "ats": "greenhouse", "slug": "instacart"},
    {"name": "Robinhood", "ats": "greenhouse", "slug": "robinhood"},
    {"name": "Coinbase", "ats": "greenhouse", "slug": "coinbase"},
    {"name": "Block", "ats": "greenhouse", "slug": "block"},
    {"name": "Twilio", "ats": "greenhouse", "slug": "twilio"},
    {"name": "Datadog", "ats": "greenhouse", "slug": "datadog"},
    {"name": "MongoDB", "ats": "greenhouse", "slug": "mongodb"},
    {"name": "Elastic", "ats": "greenhouse", "slug": "elastic"},
    {"name": "Okta", "ats": "greenhouse", "slug": "okta"},
    {"name": "Cloudflare", "ats": "greenhouse", "slug": "cloudflare"},
    {"name": "Figma", "ats": "greenhouse", "slug": "figma"},
    {"name": "Asana", "ats": "greenhouse", "slug": "asana"},
    {"name": "GitLab", "ats": "greenhouse", "slug": "gitlab"},
    {"name": "Vercel", "ats": "greenhouse", "slug": "vercel"},
    {"name": "Netlify", "ats": "greenhouse", "slug": "netlify"},
    {"name": "Postman", "ats": "greenhouse", "slug": "postman"},
    {"name": "Amplitude", "ats": "greenhouse", "slug": "amplitude"},
    {"name": "Mixpanel", "ats": "greenhouse", "slug": "mixpanel"},
    {"name": "Databricks", "ats": "greenhouse", "slug": "databricks"},
    {"name": "DeepMind", "ats": "greenhouse", "slug": "deepmind"},
    {"name": "Inflection AI", "ats": "greenhouse", "slug": "inflectionai"},
    {"name": "Jasper", "ats": "greenhouse", "slug": "jasper"},
    {"name": "Descript", "ats": "greenhouse", "slug": "descript"},
    {"name": "Figure", "ats": "greenhouse", "slug": "figure"},
    {"name": "Agility Robotics", "ats": "greenhouse", "slug": "agilityrobotics"},
    {"name": "Locus Robotics", "ats": "greenhouse", "slug": "locusrobotics"},
    {"name": "Ginkgo Bioworks", "ats": "greenhouse", "slug": "ginkgobioworks"},
    {"name": "PathAI", "ats": "greenhouse", "slug": "pathai"},
    {"name": "Viz.ai", "ats": "greenhouse", "slug": "vizai"},
    {"name": "Omada Health", "ats": "greenhouse", "slug": "omadahealth"},
    {"name": "Paradigm", "ats": "greenhouse", "slug": "paradigm"},
    {"name": "Magic Eden", "ats": "greenhouse", "slug": "magiceden"},
    {"name": "Solana Labs", "ats": "greenhouse", "slug": "solanalabs"},
    {"name": "New Relic", "ats": "greenhouse", "slug": "newrelic"},
    {"name": "CircleCI", "ats": "greenhouse", "slug": "circleci"},
    {"name": "JFrog", "ats": "greenhouse", "slug": "jfrog"},
    {"name": "PagerDuty", "ats": "greenhouse", "slug": "pagerduty"},
    {"name": "LaunchDarkly", "ats": "greenhouse", "slug": "launchdarkly"},
    {"name": "Expel", "ats": "greenhouse", "slug": "expel"},
    {"name": "Cybereason", "ats": "greenhouse", "slug": "cybereason"},
    {"name": "Huntress", "ats": "greenhouse", "slug": "huntress"},
    {"name": "JetBrains", "ats": "greenhouse", "slug": "jetbrains"},
    {"name": "Orca Security", "ats": "greenhouse", "slug": "orcasecurity"},
    {"name": "StackBlitz", "ats": "greenhouse", "slug": "stackblitz"},
    {"name": "Buildkite", "ats": "greenhouse", "slug": "buildkite"},
    {"name": "Anthropic", "ats": "greenhouse", "slug": "anthropic"},
    {"name": "Scale AI", "ats": "greenhouse", "slug": "scaleai"},
    {"name": "Brex", "ats": "greenhouse", "slug": "brex"},
    {"name": "Mercury", "ats": "greenhouse", "slug": "mercury"},
    {"name": "Gusto", "ats": "greenhouse", "slug": "gusto"},
    {"name": "Carta", "ats": "greenhouse", "slug": "carta"},
    {"name": "Benchling", "ats": "greenhouse", "slug": "benchling"},
    {"name": "Webflow", "ats": "greenhouse", "slug": "webflow"},
    {"name": "Airtable", "ats": "greenhouse", "slug": "airtable"},
    {"name": "Retool", "ats": "greenhouse", "slug": "retool"},
    {"name": "Temporal", "ats": "greenhouse", "slug": "temporal"},
    {"name": "PlanetScale", "ats": "greenhouse", "slug": "planetscale"},
    {"name": "Stability AI", "ats": "greenhouse", "slug": "stabilityai"},
    {"name": "Intercom", "ats": "greenhouse", "slug": "intercom"},
    {"name": "Salesloft", "ats": "greenhouse", "slug": "salesloft"},
    {"name": "Apollo", "ats": "greenhouse", "slug": "apollo"},
    {"name": "ZoomInfo", "ats": "greenhouse", "slug": "zoominfo"},
    {"name": "6sense", "ats": "greenhouse", "slug": "6sense"},
    {"name": "Cognism", "ats": "greenhouse", "slug": "cognism"},
    {"name": "Canonical", "ats": "greenhouse", "slug": "canonical"},
    {"name": "SingleStore", "ats": "greenhouse", "slug": "singlestore"},
    {"name": "Neo4j", "ats": "greenhouse", "slug": "neo4j"},
    {"name": "Cockroach Labs", "ats": "greenhouse", "slug": "cockroachlabs"},
    {"name": "Redis", "ats": "greenhouse", "slug": "redis"},
    {"name": "Fivetran", "ats": "greenhouse", "slug": "fivetran"},
    {"name": "Fastly", "ats": "greenhouse", "slug": "fastly"},
    {"name": "Starburst", "ats": "greenhouse", "slug": "starburst"},
    {"name": "SoFi", "ats": "greenhouse", "slug": "sofi"},
    {"name": "Chime", "ats": "greenhouse", "slug": "chime"},
    {"name": "Affirm", "ats": "greenhouse", "slug": "affirm"},
    {"name": "Bill.com", "ats": "greenhouse", "slug": "billcom"},
    {"name": "Fireblocks", "ats": "greenhouse", "slug": "fireblocks"},
    {"name": "Adyen", "ats": "greenhouse", "slug": "adyen"},
    {"name": "Alchemy", "ats": "greenhouse", "slug": "alchemy"},
    {"name": "Together AI", "ats": "greenhouse", "slug": "togetherai"},
    {"name": "Labelbox", "ats": "greenhouse", "slug": "labelbox"},
    {"name": "Arize AI", "ats": "greenhouse", "slug": "arizeai"},
    {"name": "Snorkel AI", "ats": "greenhouse", "slug": "snorkelai"},
    {"name": "Flexport", "ats": "greenhouse", "slug": "flexport"},
    {"name": "StockX", "ats": "greenhouse", "slug": "stockx"},
    {"name": "Faire", "ats": "greenhouse", "slug": "faire"},
    {"name": "Opendoor", "ats": "greenhouse", "slug": "opendoor"},
    {"name": "Oscar Health", "ats": "greenhouse", "slug": "oscarhealth"},
    {"name": "Calm", "ats": "greenhouse", "slug": "calm"},
    {"name": "Zscaler", "ats": "greenhouse", "slug": "zscaler"},
    {"name": "Bugcrowd", "ats": "greenhouse", "slug": "bugcrowd"},
    {"name": "Abnormal Security", "ats": "greenhouse", "slug": "abnormalsecurity"},
    {"name": "Tanium", "ats": "greenhouse", "slug": "tanium"},
    
    # =========================================================================
    # LEVER COMPANIES (Verified)
    # =========================================================================
    {"name": "Zoox", "ats": "lever", "slug": "zoox"},
    {"name": "Palantir", "ats": "lever", "slug": "palantir"},
    {"name": "Color Health", "ats": "lever", "slug": "color"},
    {"name": "Immutable", "ats": "lever", "slug": "immutable"},
    {"name": "Sword Health", "ats": "lever", "slug": "swordhealth"},
    {"name": "Sonatype", "ats": "lever", "slug": "sonatype"},
    {"name": "Outreach", "ats": "lever", "slug": "outreach"},
    {"name": "People.ai", "ats": "lever", "slug": "people.ai"},
    {"name": "Clari", "ats": "lever", "slug": "clari"},
    {"name": "Plaid", "ats": "lever", "slug": "plaid"},
    {"name": "Anyscale", "ats": "lever", "slug": "anyscale"},
    {"name": "Mistral AI", "ats": "lever", "slug": "mistral"},
    {"name": "Ro", "ats": "lever", "slug": "ro"},
    
    # =========================================================================
    # ASHBY COMPANIES (Verified)
    # =========================================================================
    {"name": "OpenAI", "ats": "ashby", "slug": "openai"},
    {"name": "Notion", "ats": "ashby", "slug": "notion"},
    {"name": "Snowflake", "ats": "ashby", "slug": "snowflake"},
    {"name": "ClickUp", "ats": "ashby", "slug": "clickup"},
    {"name": "Sentry", "ats": "ashby", "slug": "sentry"},
    {"name": "Ramp", "ats": "ashby", "slug": "ramp"},
    {"name": "Perplexity", "ats": "ashby", "slug": "perplexity"},
    {"name": "Railway", "ats": "ashby", "slug": "railway"},
    {"name": "Supabase", "ats": "ashby", "slug": "supabase"},
    {"name": "Render", "ats": "ashby", "slug": "render"},
    {"name": "Linear", "ats": "ashby", "slug": "linear"},
    {"name": "Modal", "ats": "ashby", "slug": "modal"},
    {"name": "Clerk", "ats": "ashby", "slug": "clerk"},
    {"name": "MotherDuck", "ats": "ashby", "slug": "motherduck"},
    {"name": "Pinecone", "ats": "ashby", "slug": "pinecone"},
    {"name": "Weaviate", "ats": "ashby", "slug": "weaviate"},
    {"name": "LangChain", "ats": "ashby", "slug": "langchain"},
    {"name": "Cohere", "ats": "ashby", "slug": "cohere"},
    {"name": "Runway", "ats": "ashby", "slug": "runway"},
    {"name": "Synthesia", "ats": "ashby", "slug": "synthesia"},
    {"name": "Pika", "ats": "ashby", "slug": "pika"},
    {"name": "ElevenLabs", "ats": "ashby", "slug": "elevenlabs"},
    {"name": "Character AI", "ats": "ashby", "slug": "character"},
    {"name": "Insitro", "ats": "ashby", "slug": "insitro"},
    {"name": "Compound", "ats": "ashby", "slug": "compound"},
    {"name": "Phantom", "ats": "ashby", "slug": "phantom"},
    {"name": "Matter Labs", "ats": "ashby", "slug": "matterlabs"},
    {"name": "Cursor", "ats": "ashby", "slug": "cursor"},
    {"name": "Replit", "ats": "ashby", "slug": "replit"},
    {"name": "Qualified", "ats": "ashby", "slug": "qualified"},
    {"name": "Demandbase", "ats": "ashby", "slug": "demandbase"},
    {"name": "Confluent", "ats": "ashby", "slug": "confluent"},
    {"name": "Chili Piper", "ats": "ashby", "slug": "chilipiper"},
    {"name": "InfluxData", "ats": "ashby", "slug": "influxdata"},
    {"name": "Airbyte", "ats": "ashby", "slug": "airbyte"},
    {"name": "Prefect", "ats": "ashby", "slug": "prefect"},
    {"name": "Astronomer", "ats": "ashby", "slug": "astronomer"},
    {"name": "Roboflow", "ats": "ashby", "slug": "roboflow"},
    {"name": "Poshmark", "ats": "ashby", "slug": "poshmark"},
    {"name": "Lemonade", "ats": "ashby", "slug": "lemonade"},
    {"name": "Whatnot", "ats": "ashby", "slug": "whatnot"},
    {"name": "HackerOne", "ats": "ashby", "slug": "hackerone"},
    {"name": "Vanta", "ats": "ashby", "slug": "vanta"},
    {"name": "Drata", "ats": "ashby", "slug": "drata"},
]

# Quick stats
TOTAL_COMPANIES = len(COMPANIES)
BY_ATS = {}
for c in COMPANIES:
    ats = c["ats"]
    BY_ATS[ats] = BY_ATS.get(ats, 0) + 1
